// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  model

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Comment ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Comment ) UnmarshalJSON([]byte) error { return nil }
func ( Comment ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Comment ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Comment *Comment

func ( CommentResp ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CommentResp ) UnmarshalJSON([]byte) error { return nil }
func ( CommentResp ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CommentResp ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CommentResp *CommentResp
